# Generated by Django 4.1.4 on 2022-12-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
    ]
