# Generated by Django 4.1.4 on 2022-12-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_topic_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislike', to='forum.customer'),
        ),
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(related_name='like', to='forum.customer'),
        ),
    ]
