# Generated by Django 4.1.4 on 2022-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_dislikes_topic_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to='forum.customer'),
        ),
    ]
